### ISSUE TITLE
Create PerkPartnerItem Component

### ISSUE THREAD

**Issue by Ottomobile** [CodeTheChangeUBC/yes-vancouver#1]
PerkPartnerItem component should be a single bar that displays the logo of the perk partner on the left and a star on the right.  See attached screenshot.  It is ok to hard code values for the image assets for now since the parent component is not ready yet.  

![image](https://user-images.githubusercontent.com/9021008/29397001-45004cb4-82d0-11e7-8feb-58f279f51d3f.png)

**Comment by rach96** [comment]
Ill do this one

**Comment by jnancy** [comment]
I can take this one!

**Comment by Ottomobile** [comment]
Component has been implemented and merged into master (PR https://github.com/CodeTheChangeUBC/yes-vancouver/pull/26)
New issues will be created and assigned in the new year.
