### ISSUE TITLE
Create ProfileDetails Component

### ISSUE THREAD

**Issue by Ottomobile** [CodeTheChangeUBC/yes-vancouver#13]
Layout text, images, buttons on ProfileDetails component.

<img width="343" alt="screen shot 2017-09-17 at 10 05 30 pm" src="https://user-images.githubusercontent.com/9021008/30529692-063641bc-9bf5-11e7-87c3-10ae5a71ca60.png">

<img width="343" alt="screen shot 2017-09-17 at 10 07 02 pm" src="https://user-images.githubusercontent.com/9021008/30529694-0b65e55c-9bf5-11e7-8fc4-82f72d4c1c18.png">

**Comment by rach96** [comment]
I'll do this one

**Comment by Ottomobile** [comment]
Completed and merged into master by Mohit (Commit d15ab10848449de2b7de657f88d1ff1ee5775ac1)
New issues will be created and assigned in the new year.
