### ISSUE TITLE
Create PerkPartnerDetails Component

### ISSUE THREAD

**Issue by Ottomobile** [CodeTheChangeUBC/yes-vancouver#2]
PerkPartnerDetails component contains details about the partner, offer, barcode, etc.  This task involves aligning the images and text elements like shown below in the screenshot.

![image](https://user-images.githubusercontent.com/9021008/29397276-eff29b62-82d1-11e7-83aa-d134b2d3b2b4.png)

**Comment by Tiffanyxu819** [comment]
I got this one

**Comment by Ottomobile** [comment]
Component has been implemented and merged into master (PR https://github.com/CodeTheChangeUBC/yes-vancouver/pull/26)
New issues will be created and assigned in the new year.
