### ISSUE TITLE
Create SignUp Component

### ISSUE THREAD

**Issue by Ottomobile** [CodeTheChangeUBC/yes-vancouver#20]
Create the four fields:
- First name
- Last name
- Email
- Password

Add header (could reuse src/components/Navigation/Header.js)
Add 'Sign up' Button
For now, can just layout the UI elements.

<img width="348" alt="screen shot 2017-11-05 at 10 52 17 pm" src="https://user-images.githubusercontent.com/9021008/32428825-ae2ffa36-c27c-11e7-8ae3-911e73274f99.png">

**Comment by mohitkewalramani7** [comment]
I'll take this one.

**Comment by Ottomobile** [comment]
Completed and merged into master by Mohit (Commit d15ab10848449de2b7de657f88d1ff1ee5775ac1)
