### ISSUE TITLE
Create ResetPassword Component

### ISSUE THREAD

**Issue by Ottomobile** [CodeTheChangeUBC/yes-vancouver#22]
Create a component with a black background and a reset password box centred on the screen.
For now, just layout UI elements.

<img width="336" alt="screen shot 2017-11-05 at 10 51 02 pm" src="https://user-images.githubusercontent.com/9021008/32429441-8b9f36c8-c27f-11e7-9b88-41c9c2acdf14.png">

**Comment by mohitkewalramani7** [comment]
I'll take this one

**Comment by Ottomobile** [comment]
Completed and merged into master by Mohit (Commit d15ab10848449de2b7de657f88d1ff1ee5775ac1)
