### ISSUE TITLE
Create PerkPartnerList Component

### ISSUE THREAD

**Issue by Ottomobile** [CodeTheChangeUBC/yes-vancouver#3]
PerkPartnerList component contains:
1. Header bar (A-Z, Categories, Favourites) - just implement UI, sorting logic can be ignored for now
2. ListView (a list of all the perk partners) - this ListView can just contain text elements as placeholders for the PerkPartnerItem components for now

![image](https://user-images.githubusercontent.com/9021008/29397411-d5841fd4-82d2-11e7-9523-1369c50910a6.png)

**Comment by judychern** [comment]
I can take this!

**Comment by Ottomobile** [comment]
Component has been implemented and merged into master (PR https://github.com/CodeTheChangeUBC/yes-vancouver/pull/26)
New issues will be created and assigned in the new year.
