### ISSUE TITLE
Create HomeScreen 

### ISSUE THREAD

**Issue by Ottomobile** [CodeTheChangeUBC/yes-vancouver#4]
Layout images, buttons, text on the home screen. Button/links don't need to redirect anywhere yet since the sign-up/login pages are not ready yet.

![image](https://user-images.githubusercontent.com/9021008/29397628-7949f9f8-82d4-11e7-96a2-286a6e1c8142.png)

**Comment by mohitkewalramani7** [comment]
I've done some work on this, Joy you can pick up from there

**Comment by Ottomobile** [comment]
Completed and merged into master by Mohit (Commit d15ab10848449de2b7de657f88d1ff1ee5775ac1)
