### ISSUE TITLE
Create LoginScreen

### ISSUE THREAD

**Issue by Ottomobile** [CodeTheChangeUBC/yes-vancouver#5]
Layout text input boxes, buttons, and text elements on LoginScreen.

![image](https://user-images.githubusercontent.com/9021008/29397759-5d33612c-82d5-11e7-9837-97d31d90105d.png)

**Comment by bonniiez** [comment]
I can take up this one : )

**Comment by Ottomobile** [comment]
Nice work Bonnie!
Merged into master: https://github.com/CodeTheChangeUBC/yes-vancouver/pull/6
